package com.example.demo.controller;

import com.example.demo.dto.CoinApiResponse;
import com.example.demo.repository.StockRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.client.RestTemplate;

@Controller
public class SampleController {


	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private StockRepository stockRepository;

	// デバッグ用テスト関数
	// 文字列加工などのちょいデバッグはここで。
    @RequestMapping("/test")
    public String test(String str) {
		String replacedStr;

		replacedStr = str.replaceAll("¥d", "");
		return replacedStr;
    }


    @RequestMapping("/coinRate")
    public String coinRate() {



		RestTemplate restTemplate = new RestTemplate();

		CoinApiResponse coinApiResponse
			= restTemplate.getForObject("https://coincheck.com/api/rate/btc_jpy", CoinApiResponse.class);
		System.out.println(coinApiResponse.getRate());
		return "sample";
		
		
    }
}