package com.example.demo.controller;

import java.util.List;

import com.example.demo.entity.Price;
import com.example.demo.service.StockService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.ModelAndView;

@Controller
public class StockController {


	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private StockService stockService;
	private Integer stockCode;

	// topページ
	@RequestMapping("/")
	public ModelAndView top(ModelAndView mav) {

		mav.setViewName("top");
		return mav;
	}

	// 値段チャート表示
	@RequestMapping("/get_rate")
	public ModelAndView get_rate(ModelAndView mav) {
		List<Price> listPrice = stockService.get_rate();

		mav.setViewName("rate");
		mav.addObject("listPrice", listPrice);
		return mav;
	}

	// 株の登録
	@RequestMapping("/add_stock")
	public String add_stock(@RequestParam int stockCode) throws Exception {

		stockService.add_stock(stockCode);
		return "sample";
		
    }
}